version: "3.9"

services: 
  socket_server:
    build: .
    container_name: socket_server
    command: python server.py
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - metrics_net
    
  agent: 
    build: .
    container_name: system_metrics_agent
    command: python producer.py
    env_file:
      - .env
    depends_on:
      - socket_server
    networks:
      - metrics_net
  
networks:
  metrics_net:
    driver: bridge